# Site settings
title: Motif of the Mind
email: junpeng.lao@unifr.ch
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the recordings of my mental roadtrip
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://junpenglao.github.io/" # the base hostname & protocol for your site
github_username:  junpenglao
owner: Junpeng Lao, PhD

# Build settings
markdown: kramdown
